package aero.nettracer.web.defaul.testing.actions;

import org.junit.Test;

import aero.nettracer.web.utility.DefaultSeleneseTestCase;

public class AuditTrailOverall extends DefaultSeleneseTestCase {

	@Test
	public void testAuditTrailOverall2() throws Exception {
		selenium.open("/tracer/logoff.do");
		selenium.type("username", "ntadmin");
		selenium.type("password", "password");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		selenium.click("menucol_8.11");
		selenium.waitForPageToLoad("30000");
		selenium.click("//td[@id='navmenucell']/div/dl/dd[11]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=9");
		selenium.waitForPageToLoad("30000");
		selenium.click("id");
		selenium.click("//input[@id='button' and @value='File Details']");
		selenium.waitForPageToLoad("30000");
		selenium.click("menucol_8.11");
		selenium.waitForPageToLoad("30000");
		selenium.click("//td[@id='navmenucell']/div/dl/dd[11]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		assertTrue(selenium.isTextPresent("Audit"));
		selenium.click("//td[@id='navmenucell']/div/dl/dd[10]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("id");
		selenium.click("//input[@id='button' and @value='File Details']");
		selenium.waitForPageToLoad("30000");
		assertTrue(selenium.isTextPresent("Audit"));
		selenium.click("//td[@id='navmenucell']/div/dl/dd[9]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=Rynns");
		selenium.waitForPageToLoad("30000");
		selenium.click("id");
		selenium.click("//input[@id='button' and @value='File Details']");
		selenium.waitForPageToLoad("30000");
		assertTrue(selenium.isTextPresent("Audit"));
		selenium.click("//td[@id='navmenucell']/div/dl/dd[8]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=SSS");
		selenium.waitForPageToLoad("30000");
		selenium.click("//input[@name='id' and @value='13']");
		selenium.click("//input[@id='button' and @value='File Details']");
		selenium.waitForPageToLoad("30000");
		assertTrue(selenium.isTextPresent("Audit"));
		selenium.click("//td[@id='navmenucell']/div/dl/dd[7]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		selenium.click("//td[@id='navmenucell']/div/dl/dd[6]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=SJO");
		selenium.waitForPageToLoad("30000");
		selenium.click("id");
		selenium.click("//input[@id='button' and @value='File Details']");
		selenium.waitForPageToLoad("30000");
		assertTrue(selenium.isTextPresent("Audit"));
		selenium.click("//td[@id='navmenucell']/div/dl/dd[5]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=nttest");
		selenium.waitForPageToLoad("30000");
		selenium.click("id");
		selenium.click("//input[@id='button' and @value='File Details']");
		selenium.waitForPageToLoad("30000");
		assertTrue(selenium.isTextPresent("Audit"));
		selenium.click("//td[@id='navmenucell']/div/dl/dd[4]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=AUAB600000426");
		selenium.waitForPageToLoad("30000");
		selenium.click("//input[@id='button' and @value='Back']");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=AUAB600000426");
		selenium.waitForPageToLoad("30000");
		selenium.click("//td[@id='navmenucell']/div/dl/dd[3]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=AUAB600000426");
		selenium.waitForPageToLoad("30000");
		selenium.click("audit_id");
		selenium.click("//input[@id='button' and @value='File Details']");
		selenium.waitForPageToLoad("30000");
		assertTrue(selenium.isTextPresent("Audit"));
		selenium.click("//td[@id='navmenucell']/div/dl/dd[2]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=BOSB600000019");
		selenium.waitForPageToLoad("30000");
		selenium.click("audit_lost_found_id");
		selenium.click("//input[@id='button' and @value='File Details']");
		selenium.waitForPageToLoad("30000");
		assertTrue(selenium.isTextPresent("Audit"));
		selenium.click("//td[@id='navmenucell']/div/dl/dd[1]/a/span[2]");
		selenium.waitForPageToLoad("30000");
		selenium.click("button");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=AUAB600000104");
		selenium.waitForPageToLoad("30000");
		selenium.click("audit_id");
		selenium.click("//input[@id='button' and @value='File Details']");
		selenium.waitForPageToLoad("30000");
		selenium.click("link=[ Logout ]");
		selenium.waitForPageToLoad("30000");
	}

}
