####RUN THIS SCRIPT INDEPENDANTLY AND VERIFY#####

--Delete Airlines from WS scripts
--select scripts
select stationdesc, station_id, companycode_id from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'));
select audit_incident_id, faultstation_ID, station.companycode_id from audit_incident inner join station on audit_incident.faultstation_id=station.station_id where faultstation_ID in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
select incident_id, faultstation_ID, station.companycode_id from incident inner join station on incident.faultstation_id=station.station_id where faultstation_ID in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
select audit_id, companycode_ID from audit_company_irregularity_codes where audit_company_irregularity_codes.companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'));
select code_id, companycode_ID from company_irregularity_codes  where company_irregularity_codes.companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'));
select ID, audit_company from audit_company_specific_variable where audit_company in (select audit_companycode.audit_id from audit_companycode where CompanyCode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
select audit_id, CompanyCode_ID, companydesc from audit_companycode where CompanyCode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'));
select ohd_id, faultstation_ID, station.companycode_ID from ohd inner join station on ohd.faultstation_ID=station.station_id where faultstation_ID in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
select ohd_id, holding_station_ID, station.companycode_ID from ohd inner join station on ohd.holding_station_ID=station.station_id where faultstation_ID in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
select ohd_id, faultstation_ID, station.companycode_ID from ohd inner join station on ohd.found_station_ID=station.station_id where faultstation_ID in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
select ohd_id, OHDLog_ID, destStationCode from ohd_log where destStationCode in (select station.Station_id from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
select id, companycode_ID from company_specific_variable where company_specific_variable.companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'));
select companycode_id, companydesc, variablecode from companycode where companycode.variablecode in (select companycode_id from company_specific_variable where company_specific_variable.companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
select code_id, companycode_id, loss_code from company_irregularity_codes  where company_irregularity_codes.companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'));
select incident_id, loss_code, faultstation_ID, station.stationCode from incident inner join station on incident.faultstation_id=station.station_id where faultstation_ID in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'))) and loss_code in (select loss_code from company_irregularity_codes  where company_irregularity_codes.companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
  --No result for above query

select a.code_id, a.companycode_id, a.loss_code, b.code_id, b.companycode_ID, b.loss_code from (select code_id, companycode_id, loss_code from company_irregularity_codes  where company_irregularity_codes.companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'))) as a inner join (select code_id, companycode_id, loss_code from company_irregularity_codes  where company_irregularity_codes.companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('WestJet'))) as b on a.loss_code = b.loss_code;
--557 rows in production

--update scripts
update incident set faultstation_ID=(select station_ID from station where companycode_ID='WS' and Stationcode='LZ') where faultstation_ID in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
update audit_incident set faultstation_ID=(select station_ID from station where companycode_ID='WS' and Stationcode='LZ') where faultstation_ID in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
update ohd set faultstation_ID=(select station_ID from station where companycode_ID='WS' and Stationcode='LZ') where faultstation_ID in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
update ohd set holding_station_ID=(select station_ID from station where companycode_ID='WS' and Stationcode='LZ') where holding_station_ID in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
update ohd set found_station_ID=(select station_ID from station where companycode_ID='WS' and Stationcode='LZ') where found_station_ID in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
update ohd_log set destStationCode=(select station_ID from station where companycode_ID='WS' and Stationcode='LZ') where destStationCode in (select station.Station_ID from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
--Delete Scripts
delete from station where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'));
delete from audit_company_irregularity_codes where audit_company_irregularity_codes.companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'));
delete from audit_companycode where companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'));
delete from audit_company_specific_variable where audit_company in (select audit_companycode.audit_id from audit_companycode where CompanyCode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air')));
delete from company_irregularity_codes  where company_irregularity_codes.companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'));
delete from company_specific_variable where company_specific_variable.companycode_ID in (select companycode.CompanyCode_ID from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air'));
delete from companycode where companydesc in ('Demo Air','Northwest Airlines', 'American Trans Air');

