package aero.nettracer.serviceprovider.common.db;

public enum ParameterType {
	RESERVATION_SYSTEM_TYPE, TEST, 
	WTSM_GET_AHL,
	WTSM_CREATE_AHL,
	WTSM_AMEND_AHL,
	WTSM_CLOSE_AHL,
	WTSM_SUSPEND_AHL,
	WTSM_REINSTATE_AHL,
	WTSM_GET_OHD,
	WTSM_CREATE_OHD,
	WTSM_AMEND_OHD,
	WTSM_CLOSE_OHD,
	WTSM_FORWARD_OHD,
	WTSM_CREATE_BDO,
	WTSM_ERASE_ACTION_FILE,
	WTSM_ACTION_FILE_COUNTS,
	WTSM_ACTION_FILE_SUMMARY,
	WTSM_ACTION_FILE_DETAILS,
	WTSM_SEND_FORWARD_MESSAGE,
	WTSM_PLACE_ACTION_FILE,
	WTSM_ESTABLISH,
	WTSM_REINSTATE_OHD,
	WTSM_SUSPEND_OHD
	
}
